In [1]:
from modules.layers import loss
import torch

In [2]:
outputs = torch.randn(2, 3, 4)
outputs = torch.abs(outputs)
outputs

tensor([[[ 0.6551,  0.6758,  0.4192,  0.5363],
         [ 0.0120,  0.4654,  1.2703,  0.3478],
         [ 0.2069,  1.0654,  1.9221,  0.9858]],

        [[ 1.3927,  0.1691,  0.9114,  0.3776],
         [ 0.7296,  1.5846,  1.6146,  0.0282],
         [ 1.6747,  0.2322,  0.2562,  0.6870]]])

In [3]:
batch = [torch.LongTensor([1, 2, 0]), torch.LongTensor([3, 1, 2])]

In [4]:
start_y = batch[-2]
end_y = batch[-1]
start_pred, end_pred = torch.max(outputs, dim=2)[1]

In [5]:
start_tmp = torch.max(start_y, start_pred)
end_tmp = torch.min(end_y, end_pred)

In [6]:
tmp = end_tmp - start_tmp + 1
tmp

tensor([ 0,  0, -1])

In [7]:
tmp = torch.max(tmp, tmp.new_zeros(tmp.size()))
tmp

tensor([ 0,  0,  0])

In [8]:
mask = tmp.eq(0)
mask

tensor([ 1,  1,  1], dtype=torch.uint8)

In [9]:
interval_y = end_y - start_y + 1
interval_y

tensor([ 3,  0,  3])

In [10]:
interval_pred = end_pred - start_pred + 1
interval_pred

tensor([ 0,  1, -1])

In [11]:
mask_y = interval_y.eq(0)
mask_y

tensor([ 0,  1,  0], dtype=torch.uint8)

In [12]:
interval_y.masked_fill_(mask_y, 1)
interval_y

tensor([ 3,  1,  3])

In [13]:
mask_pred = interval_pred.eq(0)
mask_pred

tensor([ 1,  0,  0], dtype=torch.uint8)

In [14]:
interval_pred.masked_fill_(mask_pred, 1)
interval_pred

tensor([ 1,  1, -1])

In [15]:
prec = tmp / interval_pred
prec

tensor([ 0,  0,  0])

In [16]:
rec = tmp / interval_y
rec

tensor([ 0,  0,  0])

In [17]:
((1 + 1.2**2) * prec * rec)

tensor([ 0,  0,  0])

In [1]:
(rec + 1.2**2*prec + 1e-6)

NameError: name 'rec' is not defined

In [ ]:
score = ((1 + 1.2**2) * prec * rec) / (rec + 1.2**2*prec + 1e-6)
score

In [ ]:

        

        
        
        
        

        
        

        
        score.masked_fill_(mask, 0)
        score.masked_fill_(mask_y, 0)
        score.masked_fill_(mask_pred, 0)

        score = torch.mean(score)

        # mle
        loss_mle = self.mle(outputs, batch)

        loss_value = loss_mle + self.lam * score
        
        

        
        
        
        
        

        