# test

In [3]:
import jieba
from rouge import Rouge
import numpy as np
import rouge
import matplotlib
import torch
from torch import nn
from modules import r_net
from config import config_r_net
config = config_r_net.config

In [6]:
param = {
        'embedding': np.random.random(size=(300, 400)),
        'embedding_type': config.embedding_type,
        'embedding_is_training': config.embedding_is_training,
        'mode': config.mode,
        'hidden_size': config.hidden_size,
        'dropout_p': config.dropout_p,
        'encoder_dropout_p': config.encoder_dropout_p,
        'encoder_bidirectional': config.encoder_bidirectional,
        'encoder_layer_num': config.encoder_layer_num,
        'is_bn': config.is_bn
    }

In [9]:
model = r_net.Model(param)

In [15]:
for name, param in model.named_parameters():
    print(name, param)


embedding.embedding.weight Parameter containing:
tensor([[ 4.8926e-01,  2.3599e-01,  1.8960e-01,  ...,  2.5297e-01,
          4.2423e-02,  4.0054e-01],
        [ 3.1493e-01,  9.5825e-01,  7.3811e-01,  ...,  3.5538e-01,
          2.4612e-03,  6.1036e-01],
        [ 5.3097e-01,  8.3023e-01,  8.5443e-01,  ...,  6.3969e-01,
          4.3315e-01,  8.9348e-01],
        ...,
        [ 1.3865e-01,  5.0062e-01,  1.6638e-01,  ...,  8.4954e-01,
          5.6805e-01,  2.4255e-01],
        [ 5.5230e-01,  4.1513e-01,  7.3971e-02,  ...,  8.7430e-01,
          5.7060e-01,  7.1330e-01],
        [ 5.3559e-01,  3.1718e-01,  4.5701e-01,  ...,  4.5355e-01,
          4.4405e-01,  9.2609e-01]], device='cuda:0')
encoder.rnn.weight_ih_l0 Parameter containing:
tensor([[ 5.5484e-02,  5.1939e-04, -6.3000e-02,  ...,  3.9380e-02,
         -5.3421e-02,  3.3947e-02],
        [ 9.1008e-02, -1.8209e-02, -5.8306e-02,  ..., -2.5704e-02,
          9.0298e-02, -2.7344e-02],
        [ 2.8773e-02,  8.9136e-02, -6.6062e-02,  

addition_rnn.rnn.bias_ih_l0 Parameter containing:
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.

In [21]:
p = []
for param in model.parameters():
    p.append(param)

In [17]:
from torch import optim

In [20]:
a = optim.Adam(model.parameters(), lr=1)